App:
  port: 
  database:
    mongoUrl: 
  logger:
    enabled: true
    level: "info"
  auth:
    key:
    tokenExpiresIn: 
  nodemailer:
    host: 
    port: 
    auth:
      user: 
      pass: 
  password:
    key: 
    tokenExpiresIn: 